# Generated by Django 3.2.8 on 2021-10-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Response_alias_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_response_trigger', models.TextField(blank=True, null=True)),
                ('response_variant', models.TextField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_attendance_table',
            },
        ),
        migrations.CreateModel(
            name='Common_Response_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('business_unit_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('used_count', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('dnc', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'common_responses',
            },
        ),
        migrations.CreateModel(
            name='LongcodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('businessunit_id', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('send_count', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('redirect_number', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('provider', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'long_codes',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('campaign_id', models.IntegerField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('business_unit_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.CharField(max_length=50, null=True)),
                ('send_id', models.CharField(max_length=50, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
                ('send_start', models.DateTimeField(auto_now=True)),
                ('send_end', models.DateTimeField(auto_now=True)),
                ('claimed', models.BooleanField(default=False, null=True)),
                ('claimed_time', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.CharField(max_length=50, null=True)),
                ('sent_by', models.CharField(max_length=50, null=True)),
                ('success', models.CharField(max_length=50, null=True)),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sent_status', models.BooleanField(default=False, null=True)),
                ('error_code', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('url_shorten', models.CharField(max_length=50, null=True)),
                ('tcpa', models.BooleanField(default=False, null=True)),
                ('sent_time', models.DateTimeField(auto_now=True)),
                ('count_views', models.IntegerField(blank=True, null=True)),
                ('pool_id', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('media_pdf', models.CharField(max_length=50, null=True)),
                ('message_type', models.CharField(max_length=50, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('longcode', models.CharField(max_length=50, null=True)),
                ('processed', models.BooleanField(default=False, null=True)),
                ('lookup_flag', models.BooleanField(default=False, null=True)),
                ('lookup_carrier', models.CharField(max_length=50, null=True)),
                ('lookup_line_type', models.CharField(max_length=50, null=True)),
                ('lookup_response', models.CharField(max_length=50, null=True)),
                ('original_message', models.CharField(max_length=50, null=True)),
                ('cost_ignore', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Response_messages_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('matched_response', models.TextField(blank=True, null=True)),
                ('message_id', models.TextField(blank=True, null=True)),
                ('business_unit_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('conversation_ignore', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'response_messages',
            },
        ),
        migrations.CreateModel(
            name='Employee_attendance_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField(blank=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
