# Generated by Django 3.2.8 on 2021-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20211021_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance_model',
            name='User',
        ),
        migrations.AddField(
            model_name='employee_attendance_model',
            name='user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
