# Generated by Django 3.2.8 on 2021-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20211021_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendance_model',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
