# Generated by Django 3.2.8 on 2021-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20211021_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendance_model',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='employee_attendance_model',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='employee_attendance_model',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance_model',
            name='start_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_attendance_model',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
