# Generated by Django 3.2.8 on 2021-10-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20211021_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', '1'), ('employee', '2')], default=None, max_length=10),
        ),
    ]
